[build]
  base = "frontend/cloudkitchen-app"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://my-cloud-kitchen-rtnn.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
